### ISSUE TITLE
Order Cancellation

### ISSUE THREAD

**Issue by ptrwtts** [lootexchange/lootexchange#6]
When viewing a token that has an order on it, there should be an option to cancel it. We just need the button, and then just can implement the logic.

One thing to keep in mind is that if there is multiple orders on an NFT (because you listed on multiple marketplaces or at multiple prices), the next order will become valid after the first one is cancelled. You'll need to cancel them all to truly cancel. This could lead to some weird UX (why is it back, i just cancelled!)

One way to help with this would be to have a "My Orders" page, that shows a simple list of all your orders (including duplicates), and allows you to cancel any of them. We will get an API ready for this. Probably not critical for launch, but soon after.

**Comment by georgeroman** [comment]
The SDK and backend should be ready for this:
- SDK cancelling method: https://github.com/lootexchange/lootexchange/blob/9a257af0b85ab0080958282696bb67c6994cf8a7/packages/sdk/src/helpers/wyvern.ts#L107-L156
- API which returns all valid orders of an account: https://api.loot.exchange/collections/0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7/accounts/0x1b9d39da4aab19dccfbc17a16f876effcc73eafd/orders
